INSERT INTO products (productid, productname, productdescription) VALUES
(1, 'Wireless Mouse', 'Ergonomic wireless mouse with USB receiver and adjustable DPI settings.'),
(2, 'Mechanical Keyboard', 'RGB-backlit mechanical keyboard with blue switches and compact design.'),
(3, 'Gaming Headset', 'Over-ear gaming headset with noise cancellation and surround sound.'),
(4, 'USB-C Charger', 'Fast-charging USB-C wall charger compatible with most devices.'),
(5, 'Portable Power Bank', '10000mAh power bank with dual USB output and LED indicator.'),
(6, 'Vacuum Cleaner', 'Cordless vacuum cleaner with high suction power and HEPA filter.'),
(7, 'Air Fryer', 'Oil-free air fryer with adjustable temperature and digital display.'),
(8, 'Blender', 'High-speed blender with multiple speed settings and a large pitcher.'),
(9, 'Electric Kettle', '1.5L stainless steel electric kettle with auto shut-off feature.'),
(10, 'Microwave Oven', 'Compact microwave oven with multiple pre-programmed settings.'),
(11, 'Leather Wallet', 'Genuine leather wallet with multiple card slots and coin pocket.'),
(12, 'Sunglasses', 'Polarized sunglasses with UV protection and classic design.'),
(13, 'Wristwatch', 'Water-resistant wristwatch with stainless steel band and analog display.'),
(14, 'Backpack', 'Durable backpack with multiple compartments and laptop sleeve.'),
(15, 'Running Shoes', 'Lightweight running shoes with breathable mesh upper.'),
(16, 'Novel: The Great Adventure', 'A thrilling adventure novel by best-selling author John Smith.'),
(17, 'Self-Help: Mindset Matters', 'A guide to personal growth and achieving success.'),
(18, 'Cookbook: Vegan Delights', 'Over 100 vegan recipes from around the world.'),
(19, 'Science: Space Exploration', 'An in-depth look at the history and future of space exploration.'),
(20, 'Childrens Book: The Little Explorer', 'An illustrated book for young readers about exploring nature.');